Adding download_all task to poeditor
bringg/grunt-poeditor-rs pull request #2
Opened 2016-12-12 08:49 UTC by yosiat

Adding download_all task for poeditor.
Using this we won't need to update poeditor grunt files when a new language appears.

See README.md for how this works.

Asna: https://app.asana.com/0/207822667006350/228700371960775

2016-12-12 09:25 UTC, ghost approved these changes

2016-12-13 13:06 UTC, eliranha commented on README.md
> +  },
download_all.download_all ?

2016-12-13 13:06 UTC, yosiat commented on README.md
> +  },
the first is the name of the task, the second is real grunt task.
we have `download.download` in our gruntfile under `poeditor`.

2016-12-13 13:10 UTC, eliranha requested changes

2016-12-13 13:10 UTC, eliranha commented on tasks/poeditor.js
> +                done(false);
done(err)

2016-12-13 13:10 UTC, eliranha commented on tasks/poeditor.js
> +              opts.languages = _.extend(languages, opts.languages_override || {});
_.extend(languages, opts.languages_override || {});
you can skip the || {}
.extend handles it.

2016-12-13 13:10 UTC, eliranha commented on tasks/poeditor.js
> +        body = JSON.parse(body);
use try catch for parsing json, but i think request already support json type

2016-12-13 13:10 UTC, eliranha commented on tasks/poeditor.js
> +          callback('No body.list');
callback(new Error('new body.list'));

2016-12-13 13:10 UTC, eliranha commented on tasks/poeditor.js
> +        var languagesList = _.reduce(languagesToDownload, function(result, lang) {
i think you should avoid _reduce, not the most readable function

2016-12-13 13:10 UTC, eliranha commented on tasks/poeditor.js
> +    var endpoint = 'https://poeditor.com/api/';
should be defined as const

2016-12-13 13:55 UTC, yosiat commented on README.md
> +  },
Because you and @roir asked about it, I changed it and clarified it a bit.

2016-12-13 14:05 UTC, eliranha commented on README.md
> +  },
download_languages is not the best name
thats the purpose of poeditor
why not "languages" and nested is "all"

2016-12-13 14:07 UTC, eliranha commented
once done, please use your local env to test it (need to update package json)
and deploy from clean environment to staging or app2
also test multi langs

2016-12-14 16:46 UTC, yosiat commented
@eliranha Added two features, please review:

- Allowing to pass options under download_all task - useful when you to download for two poeditor projects and you don't want global optinos
- Allowing to disable expands - for tracking app.

2016-12-14 20:48 UTC, eliranha commented on tasks/poeditor.js
> +            opts = data.download_all.options || opts;
why not extend ?

2016-12-15 06:22 UTC, yosiat commented on tasks/poeditor.js
> +            opts = data.download_all.options || opts;
changed.

2016-12-15 08:16 UTC, eliranha commented
LGTM, lets merge this next week, not today

2016-12-18 10:08 UTC, merged